const images = {
  star_2: require('./../assets/images/star_2.png'),
  star: require('./../assets/images/star.png'),
  search: require('../assets/images/search.png'),
  cross: require('../assets/images/cross.png'),
  back: require('../assets/images/backArrow.png'),
  menu: require('../assets/images/menu.png'),
  vender: require('../assets/images/vender.png'),
  welcome: require('../assets/images/welcome.png'),
  pureWorkerLogo: require('../assets/images/pureWorkerLogo.png'),
  heroPix: require('../assets/images/heroPix.png'),
  heroPix1: require('../assets/images/heroPix1.png'),
  heroPix2: require('../assets/images/heroPix2.png'),
  polygon: require('../assets/images/polygon.png'),
  profile: require('../assets/images/profile.png'),
  question: require('../assets/images/question.png'),
  polygonDown: require('../assets/images/polygonDown.png'),
  polygonForward: require('../assets/images/polygonForward.png'),
  bin: require('../assets/images/bin.png'),
  edit: require('../assets/images/edit.png'),
  time: require('../assets/images/time.png'),
  calendar: require('../assets/images/calendar.png'),
  info: require('../assets/images/info.png'),
  chat: require('../assets/images/chat_.png'),
  home: require('../assets/images/home.png'),
  notification: require('../assets/images/notification.png'),
  orders: require('../assets/images/orders.png'),

  deactivte: require('../assets/images/deactivte.png'),
  exit: require('../assets/images/exit.png'),
  help: require('../assets/images/help.png'),
  support: require('../assets/images/support.png'),
  X: require('../assets/images/X.png'),
  wallet: require('../assets/images/wallet.png'),
  save: require('../assets/images/save.png'),
  saved: require('../assets/images/saved.png'),
  star2: require('../assets/images/star2.png'),
  location: require('../assets/images/location1.png'),
};
export default images;
